### ISSUE TITLE
support precompiling the matcher

### ISSUE THREAD

**Issue by jmgnc** [oasis-open/cti-pattern-matcher#32]
Support the ability to "precompile" the pattern, so that repeated matches of the same pattern do not have to parse the pattern over and over again.

Something like how re module does it:
mat = PatternMatcherObject(pattern)
objs = mat.match(inpobjects)
objs2 = mat.match(inpobjects2)

**Comment by gtback** [comment]
Thanks for the suggestion, @jmgnc !

@chisholm and I talked about this a bit, and are considering putting a "compiled pattern" object into the pattern-validator repo (which is turning into more than just for *validating* patterns). Then we could have pattern-matcher depend on pattern-validator, and we wouldn't need to worry about keeping the parser/lexer/etc. Python files in these two repositories in sync.

Since we don't want the validator to depend on the matcher, we couldn't define the "match" function directly on that compiled pattern class, but we could either extend/encapsulate that class in the matcher, or define a function that accepts the compiled Pattern and the input objects:

```python
pattern = Pattern(pattern_string)
objs = match(pattern, inpobjects)
objs2 = match(pattern, inpobjects2)
```

Do any of those options seem inherently better/worse to you?

**Comment by jmgnc** [comment]
to me, encapsulating in the matcher class seems better to me than the function.. it's more OOP like, less type checking.

**Comment by gtback** [comment]
Makes sense. We can just create a "PatternMatcher" (or "MatchablePattern") subclass of the pattern-validator Pattern class, and define a match function on that.

**Comment by gtback** [comment]
Depends on oasis-open/cti-pattern-validator#20

**Comment by gtback** [comment]
@chisholm, I'm pretty sure we can close this based on the corresponding issues in the pattern-validator being closed. Is there anything we need in this issue?

**Comment by chisholm** [comment]
Nope, I think we can close this.

**Comment by gtback** [comment]
Yep, I just found #35 where this was fixed. Thanks!
