### ISSUE TITLE
does not support MATCHES w/ _bin data

### ISSUE THREAD

**Issue by jmgnc** [oasis-open/cti-pattern-matcher#38]
If you add the following test case to test_binary.py (https://github.com/oasis-open/cti-pattern-matcher/blob/master/stix2matcher/test/test_binary.py ):
"[binary_test:name_bin MATCHES 'alice' ]",

you will get a failure, even though it should work.  This is explicitly allowed in the spec via the statement:
In the case that the property is binary (e.g., the property name ends in _bin or _hex), then the UNICODE flag MUST NOT be specified.

**Comment by chisholm** [comment]
Hmm... I just responded to issue 39 under the assumption `MATCHES` only makes sense with textual data.  The pattern matcher doesn't support regex matching on binary data, because I didn't realize it needed to.  I guess I missed/misunderstood that part.

I couldn't find mention of a `UNICODE` flag/option (mentioned in spec section 4.2.1) on the PCRE website though.  The [pattern](http://pcre.org/current/doc/html/pcre2pattern.html#SEC13) page doesn't list it as a settable option within a regex.  The [API](http://www.pcre.org/original/doc/html/pcreapi.html#SEC11) page doesn't list it as a regex compile option either.  It's not clear to me that PCRE claims to support matching on binary data.  Seems like it considers match targets as text always, although some characters may be [unprintable](http://pcre.org/current/doc/html/pcre2pattern.html#SEC5).  That means it's not clear what that reference to the "UNICODE flag" is really trying to convey.

But I get it, regex matching should work on binary data.  I'll have to add that.

**Comment by jmgnc** [comment]
There are the PCRE_UTF* flags on compile: http://www.pcre.org/original/doc/html/pcre_compile.html

As all data in Cybox is Unicode (but encoding not specified), it is up to the implementation to decide WHICH Unicode encoding they use and use the correct flag.  It is likely that Windows will use _UTF16, while most POSIX OS's will use _UTF8, but we cannot mandate which Unicode encoding is used in the specification.

**Comment by chisholm** [comment]
Ok, so the _UTF* flags tell PCRE to decode what they're given (both pattern and target), to unicode code points, before performing the pattern match.  The STIX Pattern spec is saying don't do that (to observable values.  Patterns are always strings).

**Comment by jmgnc** [comment]
So, strings in cybox are always Unicode.  There is no encoding specified except that JSON has a default of UTF-8, but there can be JSON in UTF-16 too.   As the strings are Unicode, there is no decoding to be done, but you have to encode the unicode strings to match the UTF flag you pass to PCRE (or the python PCRE library should handle this automatically for you).

**Comment by chisholm** [comment]
> As all data in Cybox is Unicode...

Actually, section 2 of spec part 3 (Cyber Observable Core Concepts) lists 13 data types. :)  This quote is from three boxes up, but perhaps your intended meaning was more complex: All binary data in Cybox, when serialized as JSON, becomes a unicode string.  Maybe imprecise language is getting us into trouble.

> So, strings in cybox are always Unicode.

Yes, but the point was to apply patterns to instances of the cybox `binary` and `hex` types (which can collectively be thought of as "binary data").  So I understand the directive in the STIX Pattern spec to say that in the context of a match operation, if you encounter binary data in an observable, don't try to decode to unicode (it wouldn't be clear how to anyway, since there isn't generally any way to know what the encoding is).  If matching on binary data, you must interpret the regex as a "binary regex" and use the data directly.

To my mind, the implications of a "binary regex" are that the regex, which is required to be a string literal, must be convertible to binary as defined in section 4.2.4 (no code points > 255).  Higher numbered code points could never match to a byte, so it wouldn't make sense.  Also, many regex features require textual semantics.  When applying to sequences of bytes, they don't make sense.  E.g. what would the regex `\d` (match a numeric digit) mean when applied to binary data?  You'd have to ascribe textual semantics to various byte values, e.g. use ASCII interpretation.  So `\d` would match byte values in the range 48-57, inclusive.

So there are deeper considerations implied by using regexes to match binary data, which aren't spelled out in the spec, and aren't evident in the reference to the PCRE "UNICODE" flag (which doesn't seem to even exist).  The above is the way I expect my pattern matcher implementation to work since that's how Python's regexes work as far as I know, and nothing in the spec says it can't work that way.

I don't see details of JSON serializations as particularly relevant to this; all specs should be written in a serialization-neutral manner (although perhaps with an eye to making particular serializations straightforward and usable).

**Comment by jmgnc** [comment]
>> As all data in Cybox is Unicode...
> Actually, section 2 of spec part 3 (Cyber Observable Core Concepts) lists 13 data types. :) This quote is from three boxes up, but perhaps your intended meaning was more complex: All binary data in Cybox, when serialized as JSON, becomes a unicode string. Maybe imprecise language is getting us into trouble.

My "all data in Cybox is unicode" should have been qualified as string data, as clearly int or floats cannot be Unicode.  This "implied" string came from the context we were in, as we were talking about MATCHES, which can not apply to floats or ints, or many other data types.


> To my mind, the implications of a "binary regex" are that the regex, which is required to be a string literal, must be convertible to binary as defined in section 4.2.4 (no code points > 255). Higher numbered code points could never match to a byte, so it wouldn't make sense.

This is correct, and how it should be.  From my reading of the PCRE spec, this is how things are handled in the case that a unicode flag is not specified.

>Also, many regex features require textual semantics. When applying to sequences of bytes, they don't make sense. E.g. what would the regex \d (match a numeric digit) mean when applied to binary data? You'd have to ascribe textual semantics to various byte values, e.g. use ASCII interpretation. So \d would match byte values in the range 48-57, inclusive.

This is already defined by PCRE (http://www.pcre.org/original/doc/html/pcrepattern.html):
By default, characters whose code points are greater than 127 never match \d, \s, or \w, and always match \D, \S, and \W, although this may vary for characters in the range 128-255 when locale-specific matching is happening. These escape sequences retain their original meanings from before Unicode support was available, mainly for efficiency reasons. If PCRE is compiled with Unicode property support, and the PCRE_UCP option is set, the behaviour is changed so that Unicode properties are used to determine character types, as follows:

So, as you can see, it is well defined by PCRE.

> So there are deeper considerations implied by using regexes to match binary data, which aren't spelled out in the spec

Can you please let me know what they are?  I believe I have addressed all of them above.

**Comment by chisholm** [comment]
I was being conceptually pretty pedantic: All of PCRE's documentation seems to be about text.  Your quoted paragraph mentions "characters" and "code points".  How can any of that be applicable when we are not dealing with characters or code points (in binary observable data)?  Binary data is just that: _bytes_.  There are no characters.  So in that sense, there is no definition in PCRE.  We're off the reservation here, so to speak.

I know programmers blur text and binary types together because it's common in programming languages: C and C++ use "char" (or char-based) type(s) for binary data; and Python2 uses "str".  So it's no wonder it gets so confusing.  But I like keeping them distinct, and cybox does this.  If it were me, I'd go to pains to define separate operations, with separate semantics, and explicit mappings where any kind of conversion had to take place.

So here is more pedantic regex/binary specification (at least, as far as I could solidify it in my brain tonight):
- Regexes are inherently textual; many features don't make any sense on binary data.  E.g. `\d`, `\s`, etc.  Therefore, binary data must be treated as text for the purposes of pattern matching.  This is done as follows: map byte values 0-127 to characters according to ASCII (or unicode, same thing?), with their usual meanings, and map byte values 128-255 to unspecified characters which have no additional semantics.  This implies that regexes must not rely on any unicode property or feature of any character with codepoint > 127.
    * Are you allowed to say in the spec that "behavior is indeterminate when locale-specific matching is happening?  Is this what you'd call 'well defined'?  Perhaps this is just a case of not letting perfect be the enemy of the good.
- Regexes are expressed as string literals; if a regex string in a pattern has any character with code point > 255, the match must eval to False, per 4.2.4.
    * (Although, the high-codepoint char could be optional in the pattern, and it would technically not be a problem; it would just never match anything.)
- Regexes may attempt to match high codepoint characters in other ways, e.g. `\x{...}`.  Regexes like this are exempt from the 4.2.4 restriction, but that might never match anything in the target binary sequence.  Evaluation to True is possible, if that character was optional.
- Regexes may include checks of Unicode properties....
    * Not sure what to do about this.  The paragraph you quoted is only part of the story.  E.g. it defines what `\d` means when unicode property support (PCRE_UCP) is turned on or off, but doesn't define what `\p{Nd}` means.  I expect it would lose its special meaning without PCRE_UCP, but would it be an error?  Should it be an error?
    * It may not be possible to disable syntax like this in all cases (e.g. Java's regex API).  If the spec mandates that an error should occur, does that mean such pattern matcher implementations must manually check regexes for `\p{...}` sequences and produce errors if they are found?

So, I think I've actually reversed course a little bit: the first bullet is actually describing bringing the binary data into the textual realm, instead of trying to push the regex into the binary realm (a "binary regex" as I had initially described it).  I decided that `\s`, `\d`, etc are just too common, and they require text.  You _must_ have textual semantics to have any meaning for those features.  So there is no choice.  Maybe you could even ditch the 4.2.4 restriction, if regexes don't have to change?  (Not that that's possible at this point.)

Anyway, I'm not going to try for a perfect Python implementation, I'm just going to use `re` and hopefully that will be good enough :)  (And it does admit its weakness with regards to unicode, at least in the Python3 re docs.)

**Comment by jmgnc** [comment]
> Are you allowed to say in the spec that "behavior is indeterminate when locale-specific matching is happening? Is this what you'd call 'well defined'? Perhaps this is just a case of not letting perfect be the enemy of the good.

No, I am not.  I am saying use the Unix standard C locale for matching in this case.

> Regexes are expressed as string literals; if a regex string in a pattern has any character with code point > 255, the match must eval to False, per 4.2.4.

Correct.

Please make sure you read: http://www.pcre.org/original/doc/html/pcreunicode.html

There are useful things like:
> In order process UTF-8 strings, you must build PCRE's 8-bit library with UTF support, and, in addition, you must call pcre_compile() with the PCRE_UTF8 option flag, or the pattern must start with the sequence (*UTF8) or (*UTF). When either of these is the case, both the pattern and any subject strings that are matched against it are treated as UTF-8 strings instead of strings of individual 1-byte characters.

I was attempting to do some testing on Python3 w/ pcre, but due to brokenness w/ pip, I am unable to verify that passing in a bytes to pcre for matching will work properly.  It should as it's clearly supported when a Unicode flag is not specified per the description mentioned above.

P.S. Using re will be an issue, and if you do, you need to make sure that it is very clear that the code is NOT a reference implementation and has this limitation that regular expressions are not compatible w/ the STIX patterning.

**Comment by chisholm** [comment]
I didn't know there were python bindings for PCRE.  I tried installing python-pcre, but it says you need msvc-14 to build the C part.  Ah well.

As far as binary matching, I think re does the right thing, ignoring unicode properties on codepoints > 127 but using them when matching textual strings.  I think the problems may arise for the more usual textual string matching, e.g. because it doesn't support some features like `\p{...}` at all.  Perhaps [regex](https://pypi.python.org/pypi/regex/) would be preferable?

I did some experimentation with Java (just to pick some other commonly used regex package), and was unable to get the correct behavior with the standard `java.util.regex` package.  Applying regexes to binary data seems like an unusual thing to do for most people, although cybersecurity folk probably do it extensively in looking for their viral signatures.  Makes me wonder what they use (I've never built anything like that).  Probably a lot of custom engines.  Anyway, some people may have to look outside their customary modules to find something that satisfies spec requirements.

**Comment by jmgnc** [comment]
Yes, it is necessary that the patterning language supports matching on "binary" data, not just text in order to support many use cases.  There was a large debate about which regex library, and it was decided to use pcre because of the fact that language bindings exist for most libraries, and that most language's regex libraries are not compatible.  We could have spend months defining a new regex language and require everyone to implement a converter to their preferred regex engine, but it was decided that was too complicated, so it was agreed upon to use PCRE as the implementation.

**Comment by gtback** [comment]
Fixed by #44
